apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: apps
  namespace: ai
  labels:
    release: promstack
spec:
  selector: {}
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - ai
